CATEGORIAS_RECEITA = {
    "SALÁRIO": [
        "TRE",
        "OUTRO SALÁRIO",
    ],
    "RENDA EXTRA": [
        "SERVIÇO EXTRA",
        "FREELANCER",
        "VENDA",
        "OUTROS",
    ],
    "REEMBOLSO": [
        "REEMBOLSO",
        "DEVOLUÇÃO",
    ],
    "OUTRAS RECEITAS": [
        "DIVERSOS",
    ],
}


CATEGORIAS_DESPESA = {
    "PESSOAIS": [
        "VESTUÁRIO",
        "BARBEARIA",
        "CUIDADOS PESSOAIS",
        "PRESENTES",
        "OUTROS",
    ],
    "CASA": [
        "CONDOMÍNIO",
        "ENERGIA ELÉTRICA",
        "ÁGUA",
        "INTERNET",
        "SECRETÁRIA",
        "MANUTENÇÃO",
        "MÓVEIS/ELETRO",
        "OUTROS",
    ],
    "ALIMENTAÇÃO": [
        "SUPERMERCADO",
        "RESTAURANTE",
        "FEIRA/SACOLÃO",
        "ÁGUA MINERAL",
        "LANCHES",
        "PADARIA",
        "OUTROS",
    ],
    "SAÚDE": [
        "PLANO DE SAÚDE",
        "FARMÁCIA",
        "CONSULTA",
        "EXAMES",
        "ODONTOLOGIA",
        "OUTROS",
    ],
    "EDUCAÇÃO": [
        "ESCOLA",
        "CURSO",
        "MATERIAL ESCOLAR",
        "LIVROS",
        "OUTROS",
    ],
    "TRANSPORTE": [
        "COMBUSTÍVEL",
        "UBER/99",
        "MANUTENÇÃO VEÍCULO",
        "ESTACIONAMENTO",
        "IPVA",
        "SEGURO VEÍCULO",
        "OUTROS",
    ],
    "COMUNICAÇÃO": [
        "CELULAR",
        "INTERNET",
        "STREAMING",
        "ASSINATURAS",
        "OUTROS",
    ],
    "LAZER": [
        "VIAGEM",
        "PASSEIO",
        "CINEMA",
        "RESTAURANTE LAZER",
        "OUTROS",
    ],
    "OUTROS": [
        "DIVERSOS",
    ],
}


SITUACOES = [
    "PREVISTO",
    "RESERVADO",
    "PAGO",
    "PENDENTE",
    "RECEBIDO",
    "CANCELADO",
]


FORMAS_PAGAMENTO = [
    "PIX",
    "CARTÃO",
    "DÉBITO",
    "DINHEIRO",
    "BOLETO",
    "CONTA",
    "TRANSFERÊNCIA",
]


CONTAS = [
    "BANCO PRINCIPAL",
    "BANCO ALIMENTAÇÃO",
    "BANCO DO BRASIL",
    "CAIXA",
    "NUBANK",
    "PAGBANK",
    "HIPERCARD",
    "PICPAY",
    "COFRE",
    "EM MÃOS",
    "OUTROS",
]


MESES = [
    ("JAN", "Janeiro"),
    ("FEV", "Fevereiro"),
    ("MAR", "Março"),
    ("ABR", "Abril"),
    ("MAI", "Maio"),
    ("JUN", "Junho"),
    ("JUL", "Julho"),
    ("AGO", "Agosto"),
    ("SET", "Setembro"),
    ("OUT", "Outubro"),
    ("NOV", "Novembro"),
    ("DEZ", "Dezembro"),
]


ORCAMENTO_PADRAO = [
    {
        "tipo": "DESPESA",
        "categoria": "ALIMENTAÇÃO",
        "subcategoria": "SUPERMERCADO",
        "descricao": "Supermercado",
        "valor_padrao": "2000,00",
        "situacao": "RESERVADO",
        "forma_pagamento": "TRANSFERÊNCIA",
        "conta": "BANCO ALIMENTAÇÃO",
        "dia_base": 1,
        "observacao": "Valor reservado no início do mês para supermercado.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "ALIMENTAÇÃO",
        "subcategoria": "RESTAURANTE",
        "descricao": "Restaurante",
        "valor_padrao": "2000,00",
        "situacao": "RESERVADO",
        "forma_pagamento": "TRANSFERÊNCIA",
        "conta": "BANCO ALIMENTAÇÃO",
        "dia_base": 1,
        "observacao": "Valor reservado no início do mês para restaurante.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "ALIMENTAÇÃO",
        "subcategoria": "FEIRA/SACOLÃO",
        "descricao": "FLV / Feira / Sacolão",
        "valor_padrao": "500,00",
        "situacao": "RESERVADO",
        "forma_pagamento": "TRANSFERÊNCIA",
        "conta": "BANCO ALIMENTAÇÃO",
        "dia_base": 1,
        "observacao": "Valor reservado no início do mês para feira, frutas, legumes e verduras.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "ALIMENTAÇÃO",
        "subcategoria": "ÁGUA MINERAL",
        "descricao": "Água mineral",
        "valor_padrao": "0,00",
        "situacao": "RESERVADO",
        "forma_pagamento": "TRANSFERÊNCIA",
        "conta": "BANCO ALIMENTAÇÃO",
        "dia_base": 1,
        "observacao": "Valor reservado para água mineral.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "ALIMENTAÇÃO",
        "subcategoria": "PADARIA",
        "descricao": "Padaria",
        "valor_padrao": "0,00",
        "situacao": "RESERVADO",
        "forma_pagamento": "TRANSFERÊNCIA",
        "conta": "BANCO ALIMENTAÇÃO",
        "dia_base": 1,
        "observacao": "Valor reservado para padaria.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "ALIMENTAÇÃO",
        "subcategoria": "LANCHES",
        "descricao": "Lanches",
        "valor_padrao": "0,00",
        "situacao": "RESERVADO",
        "forma_pagamento": "TRANSFERÊNCIA",
        "conta": "BANCO ALIMENTAÇÃO",
        "dia_base": 1,
        "observacao": "Valor reservado para lanches.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "TRANSPORTE",
        "subcategoria": "COMBUSTÍVEL",
        "descricao": "Combustível",
        "valor_padrao": "750,00",
        "situacao": "PREVISTO",
        "forma_pagamento": "CARTÃO",
        "conta": "BANCO PRINCIPAL",
        "dia_base": 1,
        "observacao": "Valor previsto para combustível no mês.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "EDUCAÇÃO",
        "subcategoria": "ESCOLA",
        "descricao": "Escola",
        "valor_padrao": "1479,20",
        "situacao": "PREVISTO",
        "forma_pagamento": "PIX",
        "conta": "BANCO PRINCIPAL",
        "dia_base": 10,
        "observacao": "Despesa fixa prevista com escola.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "SAÚDE",
        "subcategoria": "PLANO DE SAÚDE",
        "descricao": "Plano de saúde",
        "valor_padrao": "607,93",
        "situacao": "PREVISTO",
        "forma_pagamento": "BOLETO",
        "conta": "BANCO PRINCIPAL",
        "dia_base": 10,
        "observacao": "Despesa fixa prevista com plano de saúde.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "CASA",
        "subcategoria": "CONDOMÍNIO",
        "descricao": "Condomínio AP",
        "valor_padrao": "616,68",
        "situacao": "PREVISTO",
        "forma_pagamento": "BOLETO",
        "conta": "BANCO PRINCIPAL",
        "dia_base": 10,
        "observacao": "Despesa fixa prevista com condomínio.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "CASA",
        "subcategoria": "SECRETÁRIA",
        "descricao": "Secretária",
        "valor_padrao": "0,00",
        "situacao": "PREVISTO",
        "forma_pagamento": "PIX",
        "conta": "BANCO PRINCIPAL",
        "dia_base": 10,
        "observacao": "Despesa prevista com secretária.",
    },
    {
        "tipo": "DESPESA",
        "categoria": "CASA",
        "subcategoria": "ENERGIA ELÉTRICA",
        "descricao": "Energia elétrica",
        "valor_padrao": "0,00",
        "situacao": "PREVISTO",
        "forma_pagamento": "BOLETO",
        "conta": "BANCO PRINCIPAL",
        "dia_base": 15,
        "observacao": "Despesa variável prevista. Ajustar quando chegar a conta.",
    },
]